<a href="https://colab.research.google.com/github/veerubhotla-mohan/tensorflow-developer/blob/main/tensorflow_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Fundamental concepts of tensorflow
1. Introduction to tensors
2. Getting information from tensors
3. Manipulating tensors
4. Tensors and numpy
5. Using @tf.function
6. Using GPUs with tensorflow

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.9.2


###Creating tensors with tf.constant

In [ ]:
# Creating a constant using tf.constant
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Checking number of dimensions of a tensor
scalar.ndim

0

In [ ]:
#Creating a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#Dimensins of the vector
vector.ndim

1

In [ ]:
#Creating a matrix
matrix = tf.constant([[1, 2], [3, 4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
matrix.ndim

2

**Note:**
Creating a matrix with float data type.
We can specify the data type with the dtype parameter. By default, the values are given int32 datatype if all the values are integers. 
If any of the values are float, float32 is given as the data type by default


In [ ]:
matrix_float = tf.constant([[1.6, 2.5], [3, 4]])
matrix_float

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.6, 2.5],
       [3. , 4. ]], dtype=float32)>

In [ ]:
#Explicitly specifying dtype
tensor_dtype = tf.constant([1.5, 3.2], dtype='float64')
tensor_dtype

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([1.5, 3.2])>

###Creating tensors with tf.variable

Tensors created using tf.constant cannot be modified. To create mutable tensors, use tf.Variable

In [ ]:
#Creating tensor using tf.Variable
mutable_tensor = tf.Variable([10, 7])
mutable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
#Changing a value in the mutable_tensor
print(mutable_tensor[0]) #Prints 10
# mutable_tensor[0] = 100 # Causes an error. 


tf.Tensor(10, shape=(), dtype=int32)


**Note:**
1. To change the value at an index, use .assign method
2. The .assign method cannot be used on a tensor created using tf.constant. It throws error

In [ ]:
mutable_tensor[0].assign(100)
mutable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([100,   7], dtype=int32)>

### Creating random tensors

In [ ]:
random1 = tf.random.Generator.from_seed(7) #Seed gives us reproducability
random1 = random1.normal(shape=(3,2)) #Random values from normal distribution
random2 = tf.random.Generator.from_seed(7)
random2 = random2.normal(shape=(3,2)) #Generating from the same seed gives same tensor

random1, random2, random1 == random2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
random3 = tf.random.Generator.from_seed(7)
random3 = random3.uniform(shape=(3,2)) #Random values from uniform distribution
random3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.39932835, 0.7840713 ],
       [0.67880154, 0.73395896],
       [0.5520444 , 0.10948515]], dtype=float32)>

### Shuffling order of elements in a tensor

In [ ]:
not_shuffled = tf.constant([[10, 7], [2, 5], [3, 4]])
tf.random.shuffle(not_shuffled, seed=42) #Does not affect the original tensor


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

**Important note about seed**:
Seed is of 2 types: global seed and operation-level seed. These affect the reproducibility of the operations of tf.random. Please read the documentation to find how setting seed affects the operation of tensorflow methods.
https://www.tensorflow.org/api_docs/python/tf/random/set_seed

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

### Other ways to create tensors

In [ ]:
tf.ones([10, 7]) #Creates a tensor with all ones with shape of (10, 7)

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros([10, 7]) #Creates a tensor with all zeros of shape (10, 7)

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
#Creating tensors from numpy array
import numpy as np
numpy_A = np.arange(1, 25) #Creates array of size 24
A = tf.constant(numpy_A) #Creates a tensor with shape (24, )
A

<tf.Tensor: shape=(24,), dtype=int64, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

**Note:** We can create a tensor from numpy array and provide a specific shape. We need to ensure that the number of elements in the tensor based on the given shape must match the number of elements in the numpy array. In the above example, we have 24 elements in the numpy array. So the shape of the tensor can be (2, 12), (3, 8), (2, 3, 4) and even more with higher dimensions. We cannot form a tensor with shape (4, 7) because 24 != 28

In [ ]:
B = tf.constant(numpy_A, shape=(3, 8))
C = tf.constant(numpy_A, shape=(3, 2, 4))

# D = tf.constant(numpy_A, shape=(3, 9)) #NOT POSSIBLE

B, C

(<tf.Tensor: shape=(3, 8), dtype=int64, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]])>,
 <tf.Tensor: shape=(3, 2, 4), dtype=int64, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],
 
        [[ 9, 10, 11, 12],
         [13, 14, 15, 16]],
 
        [[17, 18, 19, 20],
         [21, 22, 23, 24]]])>)

### Attributes of a tensor

Attributes of a tensor are: dtype, rank(number of dimensions), shape, size

In [ ]:
t = tf.zeros([2, 3, 4, 5])
print("Data type of the elements in the tensor is", t.dtype)
print("Rank (number of dimensions) of the tensor is", t.ndim)
print("Shape of the tensor is", t.shape)
print("Size (total number of elements in the tensor) is", tf.size(t).numpy())

Data type of the elements in the tensor is <dtype: 'float32'>
Rank (number of dimensions) of the tensor is 4
Shape of the tensor is (2, 3, 4, 5)
Size (total number of elements in the tensor) is 120


### Indexing and expanding a tensor

Indexing a tensor is same as indexing a Python list. Negative indexing is also applicable

In [ ]:
#Adding a new dimension
#Method 1: Using tf.newaxis
t = tf.zeros([2, 3, 4, 5])
t_expanded = t[..., tf.newaxis] #Here ... means all the previous dimensions are copied
t_expanded.shape

TensorShape([2, 3, 4, 5, 1])

In [ ]:
#Method 2: Using tf.expand_dims
t_Expanded = tf.expand_dims(t, axis=-1) #axis can be anything in [0, D-1] where D is current dimensions. Negative indexing is also possible
t_Expanded.shape

TensorShape([2, 3, 4, 5, 1])

In [ ]:
#Reshaping a tensor
tensor = tf.constant([[10, 7, 8], [1, 2, 3]])
print(tensor.shape)
print(tf.reshape(tensor, shape=(3, 2))) #Does not change the original tensor
print(tensor.shape) #Shape is still (2, 3)

(2, 3)
tf.Tensor(
[[10  7]
 [ 8  1]
 [ 2  3]], shape=(3, 2), dtype=int32)
(2, 3)


### Operations on tensors

#### Basic operations

In [ ]:
t = tf.constant([[10, 9], [4, 0]])
print(t + 10 )
print(t - 10 )
print(t * 10 )
print(t / 10 )
print(t / 0)
print(t)
#Adds/Substracts/Multiplie or divides with 10 for each element of the tensor
#These operations do not modify the original tensor

tf.Tensor(
[[20 19]
 [14 10]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[  0  -1]
 [ -6 -10]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100  90]
 [ 40   0]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1.  0.9]
 [0.4 0. ]], shape=(2, 2), dtype=float64)
tf.Tensor(
[[inf inf]
 [inf nan]], shape=(2, 2), dtype=float64)
tf.Tensor(
[[10  9]
 [ 4  0]], shape=(2, 2), dtype=int32)


**Note:** Division with zero does not throw an error. We get "inf" or "nan"
For non-zero elements, we get "inf" meaning infinity
For zero, we get "nan" meaning not a number

**Note:** In tensorflow libray, we have math library which contains many functions like add, multiply, etc. The results look similar like using the regular operators of mathematical operations but the functions in math library provide higher speeds and it can be seen when used with large tensors. Documentation: https://www.tensorflow.org/api_docs/python/tf/math

#### Matrix multiplication

In Python, we have '@' operator to perform matrix multiplication.
If we use '*' operator, we get element wise multiplication.
In tensorflow, we can use tf.matmul function.

In [ ]:
X = tf.constant([[10, 7], [3, 4]])
Y = tf.constant([[2, 5], [8, 4]])
print(X @ Y)
print(tf.matmul(X, Y))


tf.Tensor(
[[76 78]
 [38 31]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[76 78]
 [38 31]], shape=(2, 2), dtype=int32)


In [ ]:
#Transpose of a matrix
X = tf.constant([[10, 7], [3, 4]])
print(tf.transpose(X))
print(X) #Original remains same

tf.Tensor(
[[10  3]
 [ 7  4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


#### Changing the data type of a tensor

In [ ]:
A = tf.constant([[10, 7], [3, 5]], dtype='float64')
B = tf.cast(A, dtype='float16')
print(A)
print(B)

tf.Tensor(
[[10.  7.]
 [ 3.  5.]], shape=(2, 2), dtype=float64)
tf.Tensor(
[[10.  7.]
 [ 3.  5.]], shape=(2, 2), dtype=float16)


#### Aggregating tensors

In [ ]:
#Finding min, max, mean, sum and more
E = tf.constant(np.random.randint(1, 100, size=(5, 5)))
print(E)
print(tf.reduce_min(E))
print(tf.reduce_max(E))
print(tf.reduce_sum(E))
print(tf.reduce_mean(E))

tf.Tensor(
[[ 4 70 42 67 59]
 [63 45 18 48 27]
 [23 15 43 95 25]
 [33 94 22 11  8]
 [19 73 45 24 48]], shape=(5, 5), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(95, shape=(), dtype=int64)
tf.Tensor(1021, shape=(), dtype=int64)
tf.Tensor(40, shape=(), dtype=int64)


**Note**: Variance and standard deviation are not straightforward to find.
tf.reduce_std or tf.reduce_var are not available.

Variance: 
We can find variance using tf.math.reduce_variance function. The input tensor to this function must be of float type and not int. The above tensor E is of int type. Hence convert to float.

Standard deviation:
tf.math.reduce_std function can be used with input as float

In [ ]:
#Variance 
tf.math.reduce_variance(tf.cast(E, dtype='float32'))

<tf.Tensor: shape=(), dtype=float32, numpy=629.8144>

In [ ]:
#Standard deviation
tf.math.reduce_std(tf.cast(E, dtype='float32'))

<tf.Tensor: shape=(), dtype=float32, numpy=25.096104>

#### Positional max and min

In [ ]:
F = tf.random.normal([50])
print(F)

print(tf.argmax(F)) #Returns index of the largest value
print(F[tf.argmax(F)])
      
print(tf.argmin(F)) #Returns index of the minimum value
print(F[tf.argmin(F)])

tf.Tensor(
[-1.2451378e+00  7.1700078e-01  1.9198615e-03  8.4789306e-01
 -1.1727835e+00 -1.7936139e+00 -1.6252608e+00 -1.5029508e+00
  9.2408419e-01 -1.6185147e-01 -2.2429578e-01 -7.3269784e-01
 -8.8216253e-02 -4.1798151e-01  1.5999696e+00  9.4025284e-01
  3.5586879e-01  1.8112553e+00  1.6437979e+00  1.0608644e+00
  1.6661555e+00 -6.7539817e-01  1.0388923e+00  4.8174784e-01
 -2.3895006e-01 -7.0826221e-01 -1.9990745e+00  8.4214640e-01
 -1.0676237e+00  1.5289377e+00 -2.3200946e+00 -2.3743231e+00
 -5.3324926e-01  9.9825901e-01 -4.2954931e-01  4.6497715e-01
  8.6466891e-01  1.1360300e+00 -5.2054279e-02  1.6973173e-02
  8.7116551e-01  1.0229584e-01  4.6180704e-01 -9.6379220e-01
  1.0329915e-01  6.6269726e-01  5.0127041e-01 -7.2350454e-01
 -6.9014239e-01  5.8663112e-01], shape=(50,), dtype=float32)
tf.Tensor(17, shape=(), dtype=int64)
tf.Tensor(1.8112553, shape=(), dtype=float32)
tf.Tensor(31, shape=(), dtype=int64)
tf.Tensor(-2.3743231, shape=(), dtype=float32)


#### Squeezing a tensor

In [ ]:
G = tf.random.uniform(shape=[1, 1, 1, 1, 1, 5])
print(G)

G_squeezed = tf.squeeze(G)
print(G_squeezed)

tf.Tensor([[[[[[0.5458982  0.9325112  0.6703875  0.5897664  0.09827137]]]]]], shape=(1, 1, 1, 1, 1, 5), dtype=float32)
tf.Tensor([0.5458982  0.9325112  0.6703875  0.5897664  0.09827137], shape=(5,), dtype=float32)
